ingress:
  enabled: true
  ingressClassName: nginx
  path: /
  pathType: ImplementationSpecific
  hosts:
    - <YOUR_HOST_NAME>
  tls:
   - secretName: superset-tls
     hosts:
       - <YOUR_HOST_NAME>


## Superset node configuration
supersetNode:
  connections:
    db_host: <POSTGRES_SERVICE_NAME>.NAMESPACE.svc.cluster.local
    db_port: "5432"
    db_user: <USERNAME>
    db_pass: <PASSWORD>
    db_name: superset
  
postgresql:
  enabled: false



init:
  adminUser:
    username: admin
    firstname: Superset
    lastname: Admin
    email: admin@superset.com
    password: admin